connection_string = ""

KAFKA_COUNT_TOPIC = "DataTransfer"
KAFKA_HOST_COUNTER = "localhost"
KAFKA_PORT_COUNTER = 9092
KAFKA_COUNTER_ADDR = f"{KAFKA_HOST_COUNTER}:{KAFKA_PORT_COUNTER}"

KAFKA_PROCESS_TOPIC = "DataProcess"
KAFKA_HOST_PROCESSOR = "localhost"
KAFKA_PORT_PROCESSOR = 9093
KAFKA_PROCESSOR_ADDR = f"{KAFKA_HOST_PROCESSOR}:{KAFKA_PORT_PROCESSOR}"